config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("destacame.users.urls", namespace="users")),
    path("journeys/", include("destacame.journeys.urls", namespace="journeys")),
    path("buses/", include("destacame.buses.urls", namespace="buses")),
    path("persons/", include("destacame.persons.urls", namespace="persons")),
    path("routes/", include("destacame.routes.urls", namespace="routes")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

destacame/buses/urls.py
from django.urls import path

from .views import ListBuses, CreateBuss, DetailBuss, EditBuss, DeleteBuss


app_name = "buses"
urlpatterns = [
    path("list/", view=ListBuses.as_view(), name="list"),
    path("craete/", view=CreateBuss.as_view(), name="create_buss"),
    path("detail/<int:pk>", view=DetailBuss.as_view(), name="buss_detail"),
    path("edit/<int:pk>", view=EditBuss.as_view(), name="edit_buss"),
    path("delete/<int:pk>", view=DeleteBuss.as_view(), name="delete_buss")

]

destacame/persons/urls.py
from django.urls import path

from .views import (
    ListPassengers, ListDrivers,
    create_passenger, PassengerCreateView, DriverCreate,
    PassengerDetail, DriverDetail,
    PassengerEdit, DriverEdit,
    PassengerDelete, DriverDelete
)

app_name = "persons"
urlpatterns = [
    path("list-drivers/", ListDrivers.as_view(), name='list-drivers'),
    path("list-passengers/", ListPassengers.as_view(), name='list-passengers'),

    path("create-passenger/", create_passenger, name='create-passenger'),
    path("new/", PassengerCreateView.as_view(), name='passenger_new'),
    path("new-driver/", DriverCreate.as_view(), name='driver_new'),

    path("person-detail/<int:pk>", PassengerDetail.as_view(), name="passenger_detail"),
    path("driver-detail/<int:pk>", DriverDetail.as_view(), name="driver_detail"),

    path("edit-passenger/<int:pk>", PassengerEdit.as_view(), name="passenger_edit"),
    path("edit-driver/<int:pk>", DriverEdit.as_view(), name="driver_edit"),

    path("delete-passenger/<int:pk>", PassengerDelete.as_view(), name="passenger_delete"),
    path("delete-driver/<int:pk>", DriverDelete.as_view(), name='driver_delete'),
]

destacame/routes/urls.py
from django.urls import path

from .views import ListRoutes, CreateRoute, DetailRoute, EditRoute, DeleteRoute


app_name = "routes"

urlpatterns = [
    path("list/", ListRoutes.as_view(), name="list_routes"),
    path("create/", CreateRoute.as_view(), name="create_route"),
    path("detail/<int:pk>", DetailRoute.as_view(), name="detail_route"),
    path("edit/<int:pk>", EditRoute.as_view(), name="edit_route"),
    path("delete/<int:pk>", DeleteRoute.as_view(), name="delete_route")
]

destacame/users/urls.py
from django.urls import path

from destacame.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

destacame/buses/models.py
from django.db import models
from django.urls import reverse


class Buss(models.Model):
    plate = models.CharField(max_length=12, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('buses:buss_detail', args=[str(self.id)])

destacame/journeys/models.py
import datetime
from django.urls import reverse
from django.db import models

from ..buses.models import Buss
from ..routes.models import Route
from ..persons.models import Passenger, Driver


class Journey(models.Model):
    buss = models.ForeignKey('buses.Buss', on_delete=models.CASCADE)
    route = models.ForeignKey('routes.Route', on_delete=models.CASCADE)
    passenger = models.ForeignKey('persons.Passenger', on_delete=models.CASCADE, null=True, blank=True)
    driver = models.ForeignKey('persons.Driver', on_delete=models.CASCADE, null=True)
    date = models.DateField(null=True, blank=True)
    time = models.TimeField(null=True)

    def __str__(self):
        return f'{self.route.destination}'

    def get_absolute_url(self):
        return reverse('journeys:journey_detail', args=[str(self.id)])

destacame/persons/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Passenger(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('persons:passenger_detail', args=[str(self.id)])


class Driver(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('persons:driver_detail', args=[str(self.id)])

destacame/routes/models.py
from django.db import models
from django.urls import reverse


class Route(models.Model):
    origin = models.CharField(max_length=50, blank=True, null=True)
    destination = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'{self.destination}'

    def get_absolute_url(self):
        return reverse('routes:detail_route', args=[str(self.id)])

destacame/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for destacame.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

destacame/journeys/forms.py
from django import forms
from .models import Journey


class JourneyForm(forms.ModelForm):
    class Meta:
        model = Journey
        fields = ['buss', 'route', 'passenger', 'driver', 'date', 'time']

destacame/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

destacame/buses/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Buss


class ListBuses(ListView):
    model = Buss
    context_object_name = 'buses'
    template_name = 'pages/buses/list.html'


class CreateBuss(CreateView):
    model = Buss
    template_name = 'pages/buses/create.html'
    fields = ['plate', 'name']


class DetailBuss(DetailView):
    model = Buss
    template_name = 'pages/buses/detail.html'


class EditBuss(UpdateView):
    model = Buss
    template_name = 'pages/buses/edit.html'
    fields = ['plate', 'name']


class DeleteBuss(DeleteView):
    model = Buss
    template_name = 'pages/buses/delete.html'
    success_url = reverse_lazy('buses:list')

destacame/journeys/views.py
from django.shortcuts import render
from django.views.generic import ListView, UpdateView, DetailView
from django.urls import reverse_lazy

from .models import Journey


class ListJourneys(ListView):
    model = Journey
    template_name = 'pages/journeys.html'
    context_object_name = 'journeys'


class JourneyDetail(DetailView):
    model = Journey
    template_name = 'pages/journeys/detail.html'


# class UpdateJourney(UpdateView):
#     model = Journey
#     template_name = ''
#     form_class = JourneyForm
#     success_url = reverse_lazy('')

destacame/persons/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .models import Passenger, Driver


class ListPassengers(ListView):
    model = Passenger
    context_object_name = 'passengers'
    template_name = 'pages/passengers/list.html'


class ListDrivers(ListView):
    model = Driver
    context_object_name = 'drivers'
    template_name = 'pages/drivers/list.html'


class PassengerCreateView(CreateView):
    model = Passenger
    template_name = 'pages/passengers/create.html'
    fields = ['name']


class DriverCreate(CreateView):
    model = Driver
    template_name = 'pages/drivers/create.html'
    fields = ['name']


def create_passenger(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')

        if name:
            new_user = Passenger(name=name)
            new_user.save()

    return render(request, 'pages/passengers/create.html')


class PassengerDetail(DetailView):
    model = Passenger
    template_name = 'pages/passengers/detail.html'


class DriverDetail(DetailView):
    model = Driver
    template_name = 'pages/drivers/detail.html'


class PassengerEdit(UpdateView):
    model = Passenger
    template_name = 'pages/passengers/edit_passenger.html'
    fields = ['name']


class DriverEdit(UpdateView):
    model = Driver
    template_name = 'pages/drivers/edit.html'
    fields = ['name']


class PassengerDelete(DeleteView):
    model = Passenger
    template_name = 'pages/passengers/delete.html'
    success_url = reverse_lazy('persons:list-passengers')


class DriverDelete(DeleteView):
    model = Driver
    template_name = 'pages/drivers/delete.html'
    success_url = reverse_lazy('persons:list-drivers')

destacame/routes/admin.py
from django.contrib import admin
from .models import Route

# Register your models here.
admin.site.register(Route)

destacame/routes/apps.py
from django.apps import AppConfig
from django.utils.translation import gettext_lazy as _

class RoutesConfig(AppConfig):
    # default_auto_field = 'django.db.models.BigAutoField'
    name = 'destacame.routes'
    verbose_name = _("Routes")

    def ready(self):
        try:
            pass
        except ImportError:
            pass

destacame/routes/tests.py
from django.test import TestCase

# Create your tests here.

destacame/routes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .models import Route


class ListRoutes(ListView):
    model = Route
    template_name = 'pages/routes/list.html'
    context_object_name = 'routes'


class CreateRoute(CreateView):
    model = Route
    template_name = 'pages/routes/create.html'
    fields = ['origin', 'destination']


class DetailRoute(DetailView):
    model = Route
    template_name = 'pages/routes/detail.html'


class EditRoute(UpdateView):
    model = Route
    template_name = 'pages/routes/edit.html'
    fields = ['origin', 'destination']


class DeleteRoute(DeleteView):
    model = Route
    template_name = 'pages/routes/delete.html'
    success_url = reverse_lazy('routes:list_routes')

destacame/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

destacame/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

destacame/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}destacame{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="challenge">
    <meta name="author" content="Fernando Hernandez">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body>
    <h1>Central de auto buses Mexico</h1>
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">destacame</a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'journeys:list' %}">Journeys</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'buses:list' %}">Buses</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'persons:list-drivers' %}">Drivers</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'persons:list-passengers' %}">Passengers</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'routes:list_routes' %}">Routes</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% translate "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                </li>
              {% else %}
                {% if ACCOUNT_ALLOW_REGISTRATION %}
              <li class="nav-item">
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
              </li>
              {% endif %}
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}
        <p style="text-align: center">Bienvenidos al sitio de tickets de la central de autobuses del estado de Mexico</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>